app/models.py
class News:
    '''
    News class to define News Objects
    '''

    def __init__(self, id, description, author, publishedAt, urlToImage, url):
        self.source = id
        self.description = description
        self.publishedAt = publishedAt
        self.author = author
        self.urlToImage = urlToImage
        self.url = url


class Sources:
    '''
    News class to define News Objects
    '''

    def __init__(self, id, name, url):
        self.source = id
        self.name = name
        self.url = url

app/__init__.py
from flask import Flask
from config import config_options



def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    # setting config
    from . import request
    request.configure_request(app)

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,error

app/main/views.py
from flask import render_template
from . import main
from ..request import get_cnn_news, get_bbc_news, get_aljazeera_news


# Views
@main.route('/')
def index():

    '''
    View root page function that returns the index page and its data
    '''
    title = 'Mercurial News Highlights'

    return render_template('index.html', title=title)


@main.route('/highlights/bbc')
def bbc():

    '''
    View root page function that returns the bbc highlights page and its data
    '''

    bbc_news = get_bbc_news()
    print(bbc_news)
    title = 'Mercurial News Highlights'

    return render_template('bbc-highlights.html', title=title, bbc_news=bbc_news)


@main.route('/highlights/cnn')
def cnn():

    '''
    View root page function that returns the cnn highlights page and its data
    '''

    cnn_news = get_cnn_news()
    print(cnn_news)
    title = 'Mercurial News Highlights'

    return render_template('cnn-highlights.html', title=title, cnn_news=cnn_news)


@main.route('/highlights/aljazeera')
def jaz():

    '''
    View root page function that returns the aljazeera highlights page and its data
    '''

    jaz_news = get_aljazeera_news()
    print(jaz_news)
    title = 'Mercurial News Highlights'

    return render_template('aljazeera-highlights.html', title=title, jaz_news=jaz_news)

app/templates/aljazeera-highlights.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        {% if title %}
        <title> {{ title }}</title>
        {% else %}
        <title> Mercurial News Highlights </title>
        {% endif %}
        <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
    </head>
    <body>
    <div class="w3-container w3-black w3-center w3-bar-block" style="position:fixed; height:15%; width:100%;">

     <h1>Mercurial News Highlights</h1>

    </div>
    <div class="w3-sidebar w3-bar-block w3-center" style="width:10%; top:15%">
        <br>
        <a href="{{url_for('main.index')}}" class="w3-bar-item w3-button">Home</a>
        <hr>
        <p>Our Sources</p>
        <hr>
        <a href="{{url_for('main.bbc')}}" class="w3-bar-item w3-button">BBC</a>
        <a href="{{url_for('main.cnn')}}" class="w3-bar-item w3-button">CNN</a>
        <a href="{{url_for('main.jaz')}}" class="w3-bar-item w3-button">Al-Jazeera</a>
        <hr>
        <br>
        <br>
        <img style="max-width:120px; height:auto" src="https://www.iconspng.com/images/globe-showing-africa-asia-and-europe-in-black-and-white-detailed/globe-showing-africa-asia-and-europe-in-black-and-white-detailed.jpg">
        <!--<hr>-->
    </div>
    <div class="w3-container" style="margin-left:10%; top:15%">
        <br><br><br><br><br>
        {%for jaz_news in jaz_news%}
            <div class="w3-margin w3-card-4 w3-round">
                <div class="w3-row">
                <img style="float:left; width:40%" class="w3-margin w3-round l3" src="{{jaz_news.urlToImage}}">
                    <div class="w3-margin w3-center">
                        <p><small>Published on {{jaz_news.publishedAt}}</small></p>
                        <hr>
                        <p>{{jaz_news.description}}</p>
                        <a href="{{jaz_news.url}}"><button class="w3-button w3-white w3-border">Read More Here...</button></a>
                    </div>
                </div>
            </div>
        {%endfor%}
    </div>
    </body>
</html>

app/templates/bbc-highlights.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        {% if title %}
        <title> {{ title }}</title>
        {% else %}
        <title> Mercurial News Highlights </title>
        {% endif %}
        <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
    </head>
    <body>
    <div class="w3-container w3-black w3-center w3-bar-block" style="position:fixed; height:15%; width:100%;">
     <h1>Mercurial News Highlights</h1>
    </div>
    <div class="w3-sidebar w3-bar-block w3-center" style="width:10%; top:15%">
        <br>
        <a href="{{url_for('main.index')}}" class="w3-bar-item w3-button">Home</a>
        <hr>
        <p>Our Sources</p>
        <hr>
        <a href="{{url_for('main.bbc')}}" class="w3-bar-item w3-button">BBC</a>
        <a href="{{url_for('main.cnn')}}" class="w3-bar-item w3-button">CNN</a>
        <a href="{{url_for('main.jaz')}}" class="w3-bar-item w3-button">Al-Jazeera</a>
        <hr>
        <br>
        <br>
        <img style="max-width:120px; height:auto" src="https://www.iconspng.com/images/globe-showing-africa-asia-and-europe-in-black-and-white-detailed/globe-showing-africa-asia-and-europe-in-black-and-white-detailed.jpg">

    </div>
    <div class="w3-container" style="margin-left:10%; top:15%">

        <br><br><br><br><br>
        {%for bbc_news in bbc_news%}
            <div class="w3-margin w3-card-4 w3-round">
                <div class="w3-row">
                <img style="float:left; width:40%" class="w3-margin w3-round l3" src="{{bbc_news.urlToImage}}">
                    <div class="w3-margin w3-center">
                        <p><small>Published on {{bbc_news.publishedAt}}</small></p>
                        <hr>

                        <p>{{bbc_news.description}}</p>
                        <a href="{{bbc_news.url}}"><button class="w3-button w3-white w3-border">Read More Here...</button></a>
                    </div>
                </div>
            </div>
        {%endfor%}
    </div>
    </body>
</html>

app/templates/cnn-highlights.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        {% if title %}
        <title> {{ title }}</title>
        {% else %}
        <title> Mercurial News Highlights </title>
        {% endif %}
        <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
    </head>
    <body>
    <div class="w3-container w3-black w3-center w3-bar-block" style="position:fixed; height:15%; width:100%;">

     <h1>Mercurial News Highlights</h1>

    </div>
    <div class="w3-sidebar w3-bar-block w3-center" style="width:10%; top:15%">
        <br>
        <a href="{{url_for('main.index')}}" class="w3-bar-item w3-button">Home</a>
        <hr>
        <p>Our Sources</p>
        <hr>
        <a href="{{url_for('main.bbc')}}" class="w3-bar-item w3-button">BBC</a>
        <a href="{{url_for('main.cnn')}}" class="w3-bar-item w3-button">CNN</a>
        <a href="{{url_for('main.jaz')}}" class="w3-bar-item w3-button">Al-Jazeera</a>
        <hr>
        <br>
        <br>
        <img style="max-width:120px; height:auto" src="https://www.iconspng.com/images/globe-showing-africa-asia-and-europe-in-black-and-white-detailed/globe-showing-africa-asia-and-europe-in-black-and-white-detailed.jpg">
        <!--<hr>-->
    </div>
    <div class="w3-container" style="margin-left:10%; top:15%">
        <br><br><br><br><br>
        {%for cnn_news in cnn_news%}
            <div class="w3-margin w3-card-4 w3-round">
                <div class="w3-row">
                <img style="float:left; width:40%" class="w3-margin w3-round l3" src="{{cnn_news.urlToImage}}">
                    <div class="w3-margin w3-center">
                        <p><small>Published on {{cnn_news.publishedAt}}</small></p>
                        <hr>
                        <p>{{cnn_news.description}}</p>
                        <a href="{{cnn_news.url}}"><button class="w3-button w3-white w3-border">Read More Here...</button></a>
                    </div>
                </div>
            </div>
        {%endfor%}
    </div>
    </body>
</html>

app/templates/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        {% if title %}
        <title> {{ title }}</title>
        {% else %}
        <title> Mercurial News Highlights </title>
        {% endif %}
        <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">

    </head>
    <body>
    <div class="w3-container w3-black w3-center w3-bar-block" style="position:fixed; height:15%; width:100%;">

     <h1>Mercurial News Highlights</h1>

    </div>
    <div class="w3-sidebar w3-bar-block w3-center" style="width:10%; top:15%">
        <br>
        <a href="{{url_for('main.index')}}" class="w3-bar-item w3-button">Home</a>
        <hr>
        <p>Our Sources</p>
        <hr>
        <a href="{{url_for('main.bbc')}}" class="w3-bar-item w3-button">BBC</a>
        <a href="{{url_for('main.cnn')}}" class="w3-bar-item w3-button">CNN</a>
        <a href="{{url_for('main.jaz')}}" class="w3-bar-item w3-button">Al-Jazeera</a>
        <hr>
        <br>
        <br>
        <img style="max-width:120px; height:auto" src="https://www.iconspng.com/images/globe-showing-africa-asia-and-europe-in-black-and-white-detailed/globe-showing-africa-asia-and-europe-in-black-and-white-detailed.jpg">
        <!--<hr>-->
    </div>
    <div class="w3-container w3-center" style="margin-left:10%; top:15%">
        <div class="w3-card">
            <br><br><br><br><br>
            <h2>Welcome to Mercurial News Highlights</h2>
            <br><br><br><br><br>
            <p>You can receive news updates as they happen from sources all around the world. Below are examples of credible sources our API gets news from. To get a gist of what the site is about, how about you choose a source from the links on the left sidebar... </p>
        </div>

         <img class="w3-card w3-hover-sepia" src="https://interactive.aljazeera.com/aje/live-results-us-election-day-2016/orangeicon.jpg" alt="Aljazeera" height="200" width="200">
         <img class="w3-card w3-hover-sepia" src="https://upload.wikimedia.org/wikipedia/commons/f/fb/Cnn_logo_red_background.png" alt="CNN" height="200" width="200">
         <img class="w3-card w3-hover-sepia" src="https://employees.pk/wp-content/uploads/2018/06/bbc-news.jpg" alt="BBC" height="200" width="200">
    </div>
    </body>
</html>